In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv", index_col = 0)

In [3]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [6]:
df = df.sort_values("date")

In [7]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
16086,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
16904,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
16905,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
16087,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
1225,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
11533,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
11532,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
7477,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
7476,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [8]:
df = df.reset_index(drop = True)

In [9]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [10]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [11]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [12]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys = False).apply(add_target)

/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3522436527.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("team", group_keys = False).apply(add_target)

In [13]:
df[df["team"] == "PHO"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
27,240.0,34.0,87.0,0.391,6.0,24.0,0.250,21.0,33.0,0.636,...,29.9,180.0,100.0,DAL,111,0,2016,2015-10-28,False,True
57,240.0,37.0,83.0,0.446,4.0,18.0,0.222,32.0,42.0,0.762,...,43.6,226.0,113.0,POR,92,0,2016,2015-10-30,True,True
75,240.0,39.0,94.0,0.415,11.0,32.0,0.344,12.0,16.0,0.750,...,30.4,108.0,113.0,POR,90,1,2016,2015-10-31,True,False
96,240.0,36.0,98.0,0.367,9.0,30.0,0.300,15.0,21.0,0.714,...,31.9,158.0,109.0,LAC,102,1,2016,2015-11-02,False,True
128,240.0,45.0,83.0,0.542,14.0,23.0,0.609,14.0,22.0,0.636,...,33.9,228.0,128.0,SAC,97,0,2016,2015-11-04,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17701,240.0,34.0,76.0,0.447,13.0,28.0,0.464,13.0,15.0,0.867,...,43.6,160.0,117.0,DAL,103,1,2022,2022-05-06,False,False
17708,240.0,39.0,84.0,0.464,9.0,25.0,0.360,14.0,18.0,0.778,...,40.6,187.0,117.0,DAL,111,1,2022,2022-05-08,False,True
17717,240.0,43.0,87.0,0.494,12.0,32.0,0.375,12.0,16.0,0.750,...,41.6,219.0,127.0,DAL,80,0,2022,2022-05-10,True,False
17726,240.0,31.0,78.0,0.397,6.0,18.0,0.333,18.0,21.0,0.857,...,53.2,250.0,108.0,DAL,113,1,2022,2022-05-12,False,False
17735,240.0,33.0,87.0,0.379,12.0,34.0,0.353,12.0,18.0,0.667,...,46.0,300.0,114.0,DAL,123,0,2022,2022-05-15,False,NaN

In [14]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/1618397414.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["target"][pd.isnull(df["target"])] = 2
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [15]:
df["target"] = df["target"].astype(int, errors="ignore")

In [16]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [17]:
df["won"].value_counts()

won
False    8886
True     8886
Name: count, dtype: int64

In [18]:
df["target"].value_counts()

target
1    8872
0    8870
2      30
Name: count, dtype: int64

In [19]:
nulls = pd.isnull(df)

In [20]:
nulls = nulls.sum()

In [21]:
nulls

mp          0
fg          0
fga         0
fg%         0
3p          0
           ..
home_opp    0
season      0
date        0
won         0
target      0
Length: 148, dtype: int64

In [22]:
nulls = nulls[nulls > 0]

In [23]:
nulls

+/-             17772
mp_max          17772
mp_max.1        17772
+/-_opp         17772
mp_max_opp      17772
mp_max_opp.1    17772
dtype: int64

In [24]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [25]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [26]:
df = df[valid_columns].copy()

In [27]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [28]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.6.0-cp312-cp312-macosx_12_0_arm64.whl.metadata (31 kB)
Requirement already satisfied: numpy>=1.19.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn) (2.2.0)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.0-cp312-cp312-macosx_12_0_arm64.whl (11.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 7.2 MB/s eta 0:00:00a 0:00:01
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 7.3 MB/s eta 0:00:0000:0100:01
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.0 scipy-1.14.1 threadpoolctl-3.5.0

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [125]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha = 1)
split = TimeSeriesSplit(n_splits = 3)

sfs = SequentialFeatureSelector(rr, n_features_to_select = 30, direction = "forward", cv = split)

In [126]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [127]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [128]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

ValueError: could not convert string to float: 'OKC'

In [ ]:
df

In [ ]:
sfs.fit(df[selected_columns], df["target"])

In [129]:
predictors = list(selected_columns[sfs.get_support()])

NotFittedError: This SequentialFeatureSelector instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [130]:
predictors

['fg',
 'fga',
 '3p%',
 'ts%',
 'usg%',
 'ortg',
 'ft_max',
 'orb_max',
 'pts_max',
 '+/-_max',
 'ftr_max',
 'trb%_max',
 'home',
 'fg_opp',
 '3p%_opp',
 'ft%_opp',
 'drb_opp',
 'blk_opp',
 'usg%_opp',
 'drtg_opp',
 '3p%_max_opp',
 'ft%_max_opp',
 'trb_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'trb%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp',
 'home_opp']

In [131]:
def backtest(data, model, predictors, start = 2, step = 1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train["target"])

        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index = test.index)

        combined = pd.concat([test["target"], preds], axis = 1)
        combined.columns = ["actual", "predictions"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [132]:
predictions = backtest(df, rr, predictors)

In [133]:
predictions

       actual  predictions
5761        1            1
5766        0            0
5771        0            0
5776        1            0
5781        1            0
...       ...          ...
17765       0            1
17766       1            1
17767       0            0
17768       1            1
17769       0            0

[9792 rows x 2 columns]

In [134]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["predictions"])

0.5470792483660131

In [135]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/3128703651.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.430391
1.0    0.572350
dtype: float64

In [136]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp_10_10,tov%_max_opp_10_10,usg%_max_opp_10_10,ortg_max_opp_10_10,drtg_max_opp_10_10,total_opp_10_10,home_opp_10_10,season_10_10,home_next_10,season_10
484,0.00,0.409091,0.397059,0.373206,0.206897,0.333333,0.274347,0.162791,0.190476,0.550758,...,0.08149,0.451342,0.148524,0.346019,0.453882,0.351154,0.45,2016.0,0.4,2016.0
506,0.00,0.454545,0.441176,0.392344,0.344828,0.363636,0.423990,0.395349,0.301587,0.883314,...,0.08510,0.453952,0.152632,0.348294,0.453529,0.351442,0.47,2016.0,0.5,2016.0
520,0.00,0.386364,0.279412,0.447368,0.310345,0.409091,0.344418,0.697674,0.682540,0.655776,...,0.09075,0.469308,0.116149,0.405024,0.423765,0.413942,0.40,2016.0,0.4,2016.0
521,0.00,0.477273,0.323529,0.523923,0.482759,0.378788,0.573634,0.255814,0.222222,0.766628,...,0.07649,0.482453,0.183389,0.331232,0.542824,0.351250,0.47,2016.0,0.5,2016.0
527,0.25,0.545455,0.500000,0.449761,0.310345,0.378788,0.368171,0.441860,0.365079,0.805134,...,0.07358,0.320901,0.120334,0.312085,0.412235,0.342692,0.58,2016.0,0.3,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17765,0.00,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.08511,0.397820,0.218280,0.416967,0.526235,0.345865,0.56,2022.0,0.5,2022.0
17766,0.00,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.10372,0.409465,0.213877,0.518389,0.540000,0.423846,0.41,2022.0,0.6,2022.0
17767,0.00,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.08657,0.400681,0.208639,0.418957,0.526353,0.344423,0.55,2022.0,0.5,2022.0
17768,0.00,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.10652,0.404329,0.228755,0.531517,0.543882,0.418365,0.40,2022.0,0.5,2022.0
17769,0.00,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.08863,0.409308,0.199692,0.422749,0.522118,0.343269,0.54,2022.0,0.5,2022.0

In [137]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [138]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,drtg_max_opp_10_10,total_opp_10_10,home_opp_10_10,season_10_10,home_next_10,season_10,season_10,won,team,season
484,0.00,0.409091,0.397059,0.373206,0.206897,0.333333,0.274347,0.162791,0.190476,0.550758,...,0.453882,0.351154,0.45,2016.0,0.4,2016.0,2016.0,False,ATL,2016
506,0.00,0.454545,0.441176,0.392344,0.344828,0.363636,0.423990,0.395349,0.301587,0.883314,...,0.453529,0.351442,0.47,2016.0,0.5,2016.0,2016.0,True,ATL,2016
520,0.00,0.386364,0.279412,0.447368,0.310345,0.409091,0.344418,0.697674,0.682540,0.655776,...,0.423765,0.413942,0.40,2016.0,0.4,2016.0,2016.0,True,SAC,2016
521,0.00,0.477273,0.323529,0.523923,0.482759,0.378788,0.573634,0.255814,0.222222,0.766628,...,0.542824,0.351250,0.47,2016.0,0.5,2016.0,2016.0,True,GSW,2016
527,0.25,0.545455,0.500000,0.449761,0.310345,0.378788,0.368171,0.441860,0.365079,0.805134,...,0.412235,0.342692,0.58,2016.0,0.3,2016.0,2016.0,True,DAL,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17765,0.00,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.526235,0.345865,0.56,2022.0,0.5,2022.0,2022.0,True,BOS,2022
17766,0.00,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.540000,0.423846,0.41,2022.0,0.6,2022.0,2022.0,True,GSW,2022
17767,0.00,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.526353,0.344423,0.55,2022.0,0.5,2022.0,2022.0,False,BOS,2022
17768,0.00,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.543882,0.418365,0.40,2022.0,0.5,2022.0,2022.0,True,GSW,2022
17769,0.00,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.522118,0.343269,0.54,2022.0,0.5,2022.0,2022.0,False,BOS,2022

In [139]:
def find_team_averages(team):
    numeric_team = team.select_dtypes(include=["number"])
    rolling = numeric_team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys = False).apply(find_team_averages)

/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/546001505.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_rolling = df_rolling.groupby(["team", "season"], group_keys = False).apply(find_team_averages)

In [140]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10_10,ortg_max_opp_10_10,drtg_max_opp_10_10,total_opp_10_10,home_opp_10_10,season_10_10,home_next_10,season_10,season_10,season
484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17765,0.0,0.386364,0.283824,0.441627,0.455172,0.471212,0.439667,0.458140,0.393651,0.765694,...,0.231356,0.406882,0.550118,0.369442,0.542,2022.0,0.45,2022.0,2022.0,2022.0
17766,0.0,0.502273,0.388235,0.500478,0.493103,0.501515,0.458789,0.309302,0.276190,0.741657,...,0.188714,0.513929,0.551941,0.428471,0.481,2022.0,0.60,2022.0,2022.0,2022.0
17767,0.0,0.381818,0.292647,0.428230,0.468966,0.477273,0.448100,0.434884,0.373016,0.764177,...,0.231462,0.408152,0.543400,0.363577,0.544,2022.0,0.46,2022.0,2022.0,2022.0
17768,0.0,0.502273,0.364706,0.517703,0.455172,0.481818,0.440736,0.320930,0.282540,0.757993,...,0.194884,0.518536,0.549271,0.427808,0.468,2022.0,0.60,2022.0,2022.0,2022.0
17769,0.0,0.354545,0.279412,0.404545,0.437931,0.465152,0.429572,0.434884,0.385714,0.736639,...,0.229374,0.410009,0.537459,0.358413,0.544,2022.0,0.46,2022.0,2022.0,2022.0

In [141]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis = 1)

In [142]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10_10_10,ortg_max_opp_10_10_10,drtg_max_opp_10_10_10,total_opp_10_10_10,home_opp_10_10_10,season_10_10_10,home_next_10_10,season_10_10,season_10_10,season_10
484,0.00,0.409091,0.397059,0.373206,0.206897,0.333333,0.274347,0.162791,0.190476,0.550758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,0.00,0.454545,0.441176,0.392344,0.344828,0.363636,0.423990,0.395349,0.301587,0.883314,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,0.00,0.386364,0.279412,0.447368,0.310345,0.409091,0.344418,0.697674,0.682540,0.655776,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,0.00,0.477273,0.323529,0.523923,0.482759,0.378788,0.573634,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,0.25,0.545455,0.500000,0.449761,0.310345,0.378788,0.368171,0.441860,0.365079,0.805134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17765,0.00,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.231356,0.406882,0.550118,0.369442,0.542,2022.0,0.45,2022.0,2022.0,2022.0
17766,0.00,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.188714,0.513929,0.551941,0.428471,0.481,2022.0,0.60,2022.0,2022.0,2022.0
17767,0.00,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.231462,0.408152,0.543400,0.363577,0.544,2022.0,0.46,2022.0,2022.0,2022.0
17768,0.00,0.500000,0.411765,0.471292,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.194884,0.518536,0.549271,0.427808,0.468,2022.0,0.60,2022.0,2022.0,2022.0
17769,0.00,0.272727,0.220588,0.344498,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.229374,0.410009,0.537459,0.358413,0.544,2022.0,0.46,2022.0,2022.0,2022.0

In [143]:
df = df.dropna()

In [144]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10_10_10,ortg_max_opp_10_10_10,drtg_max_opp_10_10_10,total_opp_10_10_10,home_opp_10_10_10,season_10_10_10,home_next_10_10,season_10_10,season_10_10,season_10
771,1.0,0.840909,0.941176,0.437799,0.275862,0.378788,0.327791,0.604651,0.714286,0.518086,...,0.136327,0.422820,0.413094,0.329250,0.531,2016.0,0.64,2016.0,2016.0,2016.0
772,0.0,0.522727,0.455882,0.461722,0.137931,0.212121,0.263658,0.534884,0.428571,0.833139,...,0.146009,0.417867,0.393118,0.368885,0.554,2016.0,0.46,2016.0,2016.0,2016.0
774,0.0,0.568182,0.352941,0.610048,0.206897,0.181818,0.445368,0.209302,0.253968,0.519253,...,0.129557,0.491275,0.462471,0.421913,0.566,2016.0,0.33,2016.0,2016.0,2016.0
775,0.0,0.409091,0.250000,0.507177,0.206897,0.303030,0.296912,0.372093,0.460317,0.494749,...,0.257741,0.445294,0.303165,0.363038,0.639,2016.0,0.37,2016.0,2016.0,2016.0
778,0.0,0.250000,0.294118,0.253589,0.206897,0.196970,0.419240,0.488372,0.365079,0.903151,...,0.159445,0.489332,0.420353,0.342106,0.414,2016.0,0.63,2016.0,2016.0,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17763,0.0,0.250000,0.294118,0.253589,0.517241,0.500000,0.480998,0.279070,0.253968,0.725788,...,0.229059,0.405967,0.558188,0.376058,0.537,2022.0,0.44,2022.0,2022.0,2022.0
17764,0.0,0.386364,0.264706,0.461722,0.517241,0.545455,0.445368,0.279070,0.222222,0.844807,...,0.183682,0.509668,0.554988,0.428452,0.494,2022.0,0.59,2022.0,2022.0,2022.0
17765,0.0,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.231356,0.406882,0.550118,0.369442,0.542,2022.0,0.45,2022.0,2022.0,2022.0
17766,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.188714,0.513929,0.551941,0.428471,0.481,2022.0,0.60,2022.0,2022.0,2022.0
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.231462,0.408152,0.543400,0.363577,0.544,2022.0,0.46,2022.0,2022.0,2022.0

In [145]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys = False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/2289298505.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys = False).apply(lambda x: shift_col(x, col_name))
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/2289298505.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/2289298505.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys = False).apply(lambda x: shift_col(x, col_name))
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/2289298505.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df, "team_opp")
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/2289298505.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys = False).apply(lambda x: shift_col(x, col_name))
/var/folders/5j/dkmtj8jn6_96ykqpq0jvq0f40000gn/T/ipykernel_49294/2289298505.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [146]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp_10_10_10,ortg_max_opp_10_10_10,drtg_max_opp_10_10_10,total_opp_10_10_10,home_opp_10_10_10,season_10_10_10,home_next_10_10,season_10_10,season_10_10,season_10
771,1.0,0.840909,0.941176,0.437799,0.275862,0.378788,0.327791,0.604651,0.714286,0.518086,...,0.136327,0.422820,0.413094,0.329250,0.531,2016.0,0.64,2016.0,2016.0,2016.0
772,0.0,0.522727,0.455882,0.461722,0.137931,0.212121,0.263658,0.534884,0.428571,0.833139,...,0.146009,0.417867,0.393118,0.368885,0.554,2016.0,0.46,2016.0,2016.0,2016.0
774,0.0,0.568182,0.352941,0.610048,0.206897,0.181818,0.445368,0.209302,0.253968,0.519253,...,0.129557,0.491275,0.462471,0.421913,0.566,2016.0,0.33,2016.0,2016.0,2016.0
775,0.0,0.409091,0.250000,0.507177,0.206897,0.303030,0.296912,0.372093,0.460317,0.494749,...,0.257741,0.445294,0.303165,0.363038,0.639,2016.0,0.37,2016.0,2016.0,2016.0
778,0.0,0.250000,0.294118,0.253589,0.206897,0.196970,0.419240,0.488372,0.365079,0.903151,...,0.159445,0.489332,0.420353,0.342106,0.414,2016.0,0.63,2016.0,2016.0,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17763,0.0,0.250000,0.294118,0.253589,0.517241,0.500000,0.480998,0.279070,0.253968,0.725788,...,0.229059,0.405967,0.558188,0.376058,0.537,2022.0,0.44,2022.0,2022.0,2022.0
17764,0.0,0.386364,0.264706,0.461722,0.517241,0.545455,0.445368,0.279070,0.222222,0.844807,...,0.183682,0.509668,0.554988,0.428452,0.494,2022.0,0.59,2022.0,2022.0,2022.0
17765,0.0,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,0.231356,0.406882,0.550118,0.369442,0.542,2022.0,0.45,2022.0,2022.0,2022.0
17766,0.0,0.477273,0.455882,0.409091,0.517241,0.590909,0.414489,0.255814,0.222222,0.766628,...,0.188714,0.513929,0.551941,0.428471,0.481,2022.0,0.60,2022.0,2022.0,2022.0
17767,0.0,0.340909,0.367647,0.313397,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.231462,0.408152,0.543400,0.363577,0.544,2022.0,0.46,2022.0,2022.0,2022.0

In [147]:
df = df.copy()

In [148]:
full = df.merge(
    df[rolling_cols + ["team_opp_next", "date_next", "team"]], 
    left_on = ["team", "date_next"], 
    right_on = ["team_opp_next", "date_next"]
)

In [149]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,season_10_10_y,season_10_10_y,season_10_10_y,season_10_10_y,season_10_10_y,season_10_y,season_10_y,season_10_y,team_opp_next_y,team_y
0,0.0,0.522727,0.455882,0.461722,0.137931,0.212121,0.263658,0.534884,0.428571,0.833139,...,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,MIL,PHO
1,0.0,0.568182,0.352941,0.610048,0.206897,0.181818,0.445368,0.209302,0.253968,0.519253,...,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,PHO,MIL
2,0.0,0.409091,0.338235,0.423445,0.172414,0.227273,0.312352,0.372093,0.317460,0.778296,...,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,MEM,PHI
3,0.0,0.454545,0.294118,0.523923,0.448276,0.454545,0.453682,0.395349,0.333333,0.787631,...,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,POR,ATL
4,0.0,0.250000,0.382353,0.191388,0.172414,0.303030,0.247031,0.465116,0.460317,0.649942,...,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,PHI,MEM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11823,0.0,0.454545,0.411765,0.416268,0.655172,0.621212,0.501188,0.232558,0.222222,0.688448,...,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,GSW,BOS
11824,0.0,0.454545,0.382353,0.440191,0.517241,0.500000,0.480998,0.302326,0.301587,0.649942,...,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,GSW,BOS
11825,0.0,0.250000,0.294118,0.253589,0.517241,0.500000,0.480998,0.279070,0.253968,0.725788,...,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,BOS,GSW
11826,0.0,0.386364,0.264706,0.461722,0.517241,0.545455,0.445368,0.279070,0.222222,0.844807,...,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,GSW,BOS
11827,0.0,0.545455,0.426471,0.511962,0.448276,0.469697,0.440618,0.372093,0.365079,0.659277,...,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,2022.0,BOS,GSW

In [150]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        MIL             PHO    PHO             MIL  2015-12-20
1        PHO             MIL    MIL             PHO  2015-12-20
2        MEM             PHI    PHI             MEM  2015-12-22
3        POR             ATL    ATL             POR  2015-12-21
4        PHI             MEM    MEM             PHI  2015-12-22
...      ...             ...    ...             ...         ...
11823    GSW             BOS    BOS             GSW  2022-06-05
11824    GSW             BOS    BOS             GSW  2022-06-08
11825    BOS             GSW    GSW             BOS  2022-06-08
11826    GSW             BOS    BOS             GSW  2022-06-10
11827    BOS             GSW    GSW             BOS  2022-06-10

[11828 rows x 5 columns]

In [151]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [152]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [153]:
seleted_columns = full.columns[~full.columns.isin(removed_columns)]

In [154]:
sfs.fit(full[selected_columns], full["target"])

KeyError: "['mp_10', 'fg_10', 'fga_10', 'fg%_10', '3p_10', '3pa_10', '3p%_10', 'ft_10', 'fta_10', 'ft%_10', 'orb_10', 'drb_10', 'trb_10', 'ast_10', 'stl_10', 'blk_10', 'tov_10', 'pf_10', 'pts_10', 'ts%_10', 'efg%_10', '3par_10', 'ftr_10', 'orb%_10', 'drb%_10', 'trb%_10', 'ast%_10', 'stl%_10', 'blk%_10', 'tov%_10', 'usg%_10', 'ortg_10', 'drtg_10', 'fg_max_10', 'fga_max_10', 'fg%_max_10', '3p_max_10', '3pa_max_10', '3p%_max_10', 'ft_max_10', 'fta_max_10', 'ft%_max_10', 'orb_max_10', 'drb_max_10', 'trb_max_10', 'ast_max_10', 'stl_max_10', 'blk_max_10', 'tov_max_10', 'pf_max_10', 'pts_max_10', '+/-_max_10', 'ts%_max_10', 'efg%_max_10', '3par_max_10', 'ftr_max_10', 'orb%_max_10', 'drb%_max_10', 'trb%_max_10', 'ast%_max_10', 'stl%_max_10', 'blk%_max_10', 'tov%_max_10', 'usg%_max_10', 'ortg_max_10', 'drtg_max_10', 'total_10', 'home_10', 'mp_opp_10', 'fg_opp_10', 'fga_opp_10', 'fg%_opp_10', '3p_opp_10', '3pa_opp_10', '3p%_opp_10', 'ft_opp_10', 'fta_opp_10', 'ft%_opp_10', 'orb_opp_10', 'drb_opp_10', 'trb_opp_10', 'ast_opp_10', 'stl_opp_10', 'blk_opp_10', 'tov_opp_10', 'pf_opp_10', 'pts_opp_10', 'ts%_opp_10', 'efg%_opp_10', '3par_opp_10', 'ftr_opp_10', 'orb%_opp_10', 'drb%_opp_10', 'trb%_opp_10', 'ast%_opp_10', 'stl%_opp_10', 'blk%_opp_10', 'tov%_opp_10', 'usg%_opp_10', 'ortg_opp_10', 'drtg_opp_10', 'fg_max_opp_10', 'fga_max_opp_10', 'fg%_max_opp_10', '3p_max_opp_10', '3pa_max_opp_10', '3p%_max_opp_10', 'ft_max_opp_10', 'fta_max_opp_10', 'ft%_max_opp_10', 'orb_max_opp_10', 'drb_max_opp_10', 'trb_max_opp_10', 'ast_max_opp_10', 'stl_max_opp_10', 'blk_max_opp_10', 'tov_max_opp_10', 'pf_max_opp_10', 'pts_max_opp_10', '+/-_max_opp_10', 'ts%_max_opp_10', 'efg%_max_opp_10', '3par_max_opp_10', 'ftr_max_opp_10', 'orb%_max_opp_10', 'drb%_max_opp_10', 'trb%_max_opp_10', 'ast%_max_opp_10', 'stl%_max_opp_10', 'blk%_max_opp_10', 'tov%_max_opp_10', 'usg%_max_opp_10', 'ortg_max_opp_10', 'drtg_max_opp_10', 'total_opp_10', 'home_opp_10', 'season_10', 'team_opp_next', 'mp_10_10', 'fg_10_10', 'fga_10_10', 'fg%_10_10', '3p_10_10', '3pa_10_10', '3p%_10_10', 'ft_10_10', 'fta_10_10', 'ft%_10_10', 'orb_10_10', 'drb_10_10', 'trb_10_10', 'ast_10_10', 'stl_10_10', 'blk_10_10', 'tov_10_10', 'pf_10_10', 'pts_10_10', 'ts%_10_10', 'efg%_10_10', '3par_10_10', 'ftr_10_10', 'orb%_10_10', 'drb%_10_10', 'trb%_10_10', 'ast%_10_10', 'stl%_10_10', 'blk%_10_10', 'tov%_10_10', 'usg%_10_10', 'ortg_10_10', 'drtg_10_10', 'fg_max_10_10', 'fga_max_10_10', 'fg%_max_10_10', '3p_max_10_10', '3pa_max_10_10', '3p%_max_10_10', 'ft_max_10_10', 'fta_max_10_10', 'ft%_max_10_10', 'orb_max_10_10', 'drb_max_10_10', 'trb_max_10_10', 'ast_max_10_10', 'stl_max_10_10', 'blk_max_10_10', 'tov_max_10_10', 'pf_max_10_10', 'pts_max_10_10', '+/-_max_10_10', 'ts%_max_10_10', 'efg%_max_10_10', '3par_max_10_10', 'ftr_max_10_10', 'orb%_max_10_10', 'drb%_max_10_10', 'trb%_max_10_10', 'ast%_max_10_10', 'stl%_max_10_10', 'blk%_max_10_10', 'tov%_max_10_10', 'usg%_max_10_10', 'ortg_max_10_10', 'drtg_max_10_10', 'total_10_10', 'home_10_10', 'mp_opp_10_10', 'fg_opp_10_10', 'fga_opp_10_10', 'fg%_opp_10_10', '3p_opp_10_10', '3pa_opp_10_10', '3p%_opp_10_10', 'ft_opp_10_10', 'fta_opp_10_10', 'ft%_opp_10_10', 'orb_opp_10_10', 'drb_opp_10_10', 'trb_opp_10_10', 'ast_opp_10_10', 'stl_opp_10_10', 'blk_opp_10_10', 'tov_opp_10_10', 'pf_opp_10_10', 'pts_opp_10_10', 'ts%_opp_10_10', 'efg%_opp_10_10', '3par_opp_10_10', 'ftr_opp_10_10', 'orb%_opp_10_10', 'drb%_opp_10_10', 'trb%_opp_10_10', 'ast%_opp_10_10', 'stl%_opp_10_10', 'blk%_opp_10_10', 'tov%_opp_10_10', 'usg%_opp_10_10', 'ortg_opp_10_10', 'drtg_opp_10_10', 'fg_max_opp_10_10', 'fga_max_opp_10_10', 'fg%_max_opp_10_10', '3p_max_opp_10_10', '3pa_max_opp_10_10', '3p%_max_opp_10_10', 'ft_max_opp_10_10', 'fta_max_opp_10_10', 'ft%_max_opp_10_10', 'orb_max_opp_10_10', 'drb_max_opp_10_10', 'trb_max_opp_10_10', 'ast_max_opp_10_10', 'stl_max_opp_10_10', 'blk_max_opp_10_10', 'tov_max_opp_10_10', 'pf_max_opp_10_10', 'pts_max_opp_10_10', '+/-_max_opp_10_10', 'ts%_max_opp_10_10', 'efg%_max_opp_10_10', '3par_max_opp_10_10', 'ftr_max_opp_10_10', 'orb%_max_opp_10_10', 'drb%_max_opp_10_10', 'trb%_max_opp_10_10', 'ast%_max_opp_10_10', 'stl%_max_opp_10_10', 'blk%_max_opp_10_10', 'tov%_max_opp_10_10', 'usg%_max_opp_10_10', 'ortg_max_opp_10_10', 'drtg_max_opp_10_10', 'total_opp_10_10', 'home_opp_10_10', 'season_10_10', 'home_next_10'] not in index"

In [155]:
predictors = list(selected_columns[sfs.get_support()])

NotFittedError: This SequentialFeatureSelector instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [156]:
predictors

['fg',
 'fga',
 '3p%',
 'ts%',
 'usg%',
 'ortg',
 'ft_max',
 'orb_max',
 'pts_max',
 '+/-_max',
 'ftr_max',
 'trb%_max',
 'home',
 'fg_opp',
 '3p%_opp',
 'ft%_opp',
 'drb_opp',
 'blk_opp',
 'usg%_opp',
 'drtg_opp',
 '3p%_max_opp',
 'ft%_max_opp',
 'trb_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'trb%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp',
 'home_opp']

In [157]:
predictions = backtest(full, rr, predictors)

In [158]:
accuracy_score(predictions["actual"], predictions["predictions"])

0.5439893359185652